# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaildomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=127)),
                ('time', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
