# Generated by Django 3.1.8 on 2021-05-04 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_longer_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('topic', models.CharField(choices=[('bugs', 'Bug Report'), ('suggestions', 'Suggestions'), ('accounts', 'Accounts'), ('etc', 'etc')], default='etc', max_length=11)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_mail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
