# Generated by Django 3.2.12 on 2025-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inquirymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kaist_v2_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kaist_v2_info_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
